spring.application.name=StaffManagement


server.port=8081

spring.datasource.username=${DB_USERNAME}
spring.datasource.url=jdbc:mysql://localhost:3306/flmmedsync
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
